<?php

if ( $vld != 1 ) die();

$OBJECT_ID = svc_sanitize_post( $post['object_id'] );

$sql = "
	SELECT
		OBJECT_ID,
		OBJECT_OBJTYP_ID,
		OBJECT_FOLDER_ID,
		OBJECT_NAME,
		OBJECT_ACTIVE,
		OBJECT_REV_1,
		OBJECT_REV_2,
		OBJECT_REV_3,
		OBJECT_REV_4,
		OBJECT_REV_5,
		OBJECT_REV_COMMENT_1,
		OBJECT_REV_COMMENT_2,
		OBJECT_REV_COMMENT_3,
		OBJECT_REV_COMMENT_4,
		OBJECT_REV_COMMENT_5,
		FOLDER_REVIEWER1_ID,
		FOLDER_REVIEWER2_ID,
		FOLDER_REVIEWER3_ID,
		FOLDER_REVIEWER4_ID,
		FOLDER_REVIEWER5_ID,
		CASE
			WHEN FOLDER_REVIEWER1_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER_1,
		CASE
			WHEN FOLDER_REVIEWER2_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER_2,
		CASE
			WHEN FOLDER_REVIEWER3_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER_3,
		CASE
			WHEN FOLDER_REVIEWER4_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER_4,
		CASE
			WHEN FOLDER_REVIEWER5_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER_5,
		OBJTYP_ICON,
		OBJTYP_NAME,
		CASE
			WHEN OBJECT_CREATED_BY = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS PERMISSION
	FROM
		REP_OBJECT
		INNER JOIN REP_OBJTYP
		ON OBJECT_OBJTYP_ID = OBJTYP_ID
		INNER JOIN REP_FOLDER
		ON OBJECT_FOLDER_ID = FOLDER_ID
	WHERE
		OBJECT_DOMAIN_ID = " . $DOMAIN_ID . "
		AND OBJECT_ID = " . $OBJECT_ID ."
	ORDER BY
		OBJTYP_ORDERBY,
		FN_REMOVE_ACCENTS( OBJECT_NAME )
	";


$rows = svc_get_rows( $connection, $sql );

svc_show_result_encoded( $rows[0] );



?>





