<?php

if ( $vld != 1 ) die();

$sql = "
	SELECT
		FOLDER_ID,
		FOLDER_NAME,
		CASE
			WHEN FOLDER_AUTHOR_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_AUTHOR,
		CASE
			WHEN FOLDER_REVIEWER1_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER1,
		CASE
			WHEN FOLDER_REVIEWER2_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER2,
		CASE
			WHEN FOLDER_REVIEWER3_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER3,
		CASE
			WHEN FOLDER_REVIEWER4_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER4,
		CASE
			WHEN FOLDER_REVIEWER5_ID = " . $PERSON_ID . " THEN 1
			ELSE 0
		END AS IS_REVIEWER5
	FROM
		REP_FOLDER
	WHERE
		FOLDER_DOMAIN_ID = " . $DOMAIN_ID . "
		AND (
			FOLDER_AUTHOR_ID = " . $PERSON_ID . "
			OR FOLDER_REVIEWER1_ID = " . $PERSON_ID . "
			OR FOLDER_REVIEWER2_ID = " . $PERSON_ID . "
			OR FOLDER_REVIEWER3_ID = " . $PERSON_ID . "
			OR FOLDER_REVIEWER4_ID = " . $PERSON_ID . "
			OR FOLDER_REVIEWER5_ID = " . $PERSON_ID . "
		)
	ORDER BY
		FN_REMOVE_ACCENTS( FOLDER_NAME )
	";

$rows = svc_get_rows( $connection, $sql );

svc_show_result_encoded( $rows );


?>





